/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    CreateMedicalRecord: typeof import('./src/components/CreateMedicalRecord.vue')['default']
    DeleteMedicalHistory: typeof import('./src/components/DeleteMedicalHistory.vue')['default']
    DeleteMedicalVisit: typeof import('./src/components/DeleteMedicalVisit.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ModifyMedicalHistory: typeof import('./src/components/ModifyMedicalHistory.vue')['default']
    ModifyMedicalVisit: typeof import('./src/components/ModifyMedicalVisit.vue')['default']
    RetrieveMedicalRecord: typeof import('./src/components/RetrieveMedicalRecord.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    UpdateContactInformation: typeof import('./src/components/UpdateContactInformation.vue')['default']
    UpdateMedicalHistory: typeof import('./src/components/UpdateMedicalHistory.vue')['default']
    UpdateMedicalVisit: typeof import('./src/components/UpdateMedicalVisit.vue')['default']
  }
}
